name: Test, update distribution (if not latest), and publish on release.

on:
  push:
  release:
    types: [published, edited]

jobs:
  test:
    strategy:
      matrix:
        node: ['8', '10', '12', '14']
    name: "Test on node version = ${{ matrix.node }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run test

  # this is used to ensure that the latest and greatest test
  build_and_update_dist:
    name: Build and update distribution if necessary (changed).
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
        with:
          # need to use PAT to trigger test/build if a push is done with auto-commit below
          # this ensures that the latest commit has passed status checks and can thus be merged
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2
      - run: npm ci
      # need to actually build the dist and if there are changes it will be committed
      # on top of the current commit. this ensures the github repository contains the
      # distribution materials
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # a commit will be made if any files have changed
          commit_message: Updated distribution materials.

  # could create an entire different workflow, but would have to jump through more
  # hoops to ensure that the build/tests passed without rerunning them
  publish:
    # will not run unless a release is created and the commit is tagged
    if: github.event_name == 'release' && (github.event.action == 'published') &&
      startsWith(github.ref, 'refs/tags/v')
    name: publish on release
    needs: [build_and_update_dist]
    # ensure that it is tagged -- only tagged commits are released
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm publish
